In [112]:
import numpy as np
import pandas as pd

# Basic numpy

#### Add vectors

In [113]:
[1, 2, 3]+[10, 10, 10]
# expected [11, 12, 13]

[1, 2, 3, 10, 10, 10]

In [114]:
np.array([1, 2, 3])+np.array([10, 10, 10])


array([11, 12, 13])

#### Multiply constant to vector

In [115]:
[1, 2, 3]*3
# expected [3, 6, 9]

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [116]:
np.array([1, 2, 3])*3


array([3, 6, 9])

#### Create array by range

In [117]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [118]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [119]:
np.arange(5,10,2)

array([5, 7, 9])

#### Create Array by random

In [120]:
np.random.rand(5)

array([0.25690626, 0.84363635, 0.7819984 , 0.83337752, 0.99337613])

In [121]:
np.random.randint(10,20,5)

array([15, 15, 17, 14, 14])

#### Create zero vector

In [122]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### Create one vector

In [123]:
np.ones(5)

array([1., 1., 1., 1., 1.])

#### Statistic Function

In [124]:
x = np.arange(5)*10
print(x)

[ 0 10 20 30 40]


In [125]:
x.min()

0

In [126]:
x.max()

40

In [127]:
x.std()

14.142135623730951

#### Slicing array

In [128]:
x[1:3]

array([10, 20])

In [129]:
x[0:3]

array([ 0, 10, 20])

In [130]:
x[3:]

array([30, 40])

In [131]:
x[-1]

40

# Basic Pandas

In [132]:
s1 = pd.Series([1,2,3])
print(s1)

0    1
1    2
2    3
dtype: int64


In [133]:
s1.mean()

2.0

In [134]:
s1.sum()


6

In [135]:
s2 = s1 * 10
print(s2)

0    10
1    20
2    30
dtype: int64


In [136]:
s2.mean()

20.0

In [137]:
s2.sum()

60

In [138]:
sname = pd.Series(['A','B','C'])
print(sname)

0    A
1    B
2    C
dtype: object


In [139]:
pd.DataFrame({'name':sname,'working_years':s1,'new_col':s2})

name  working_years  new_col
0    A              1       10
1    B              2       20
2    C              3       30

#### Data Frame

In [140]:
CSV_PATH = "https://rathachai.github.io/DA-LAB/datasets/simple-employee-db.csv"


In [141]:
df = pd.read_csv(CSV_PATH)


In [142]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [143]:
df.head(3)

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi

In [144]:
df.tail(3)

eid     name  gender department  age   salary  working_years birth_place
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [145]:
df['name']
# return Series

0        Anda
1      Bordin
2    Chantana
3     Donlaya
4     Ekkasit
5      Fundee
6     Gitiwit
7       Harit
Name: name, dtype: object

In [147]:
df[['name','gender']]
# return dataframe

name  gender
0      Anda  female
1    Bordin    male
2  Chantana  female
3   Donlaya  female
4   Ekkasit    male
5    Fundee  female
6   Gitiwit    male
7     Harit    male

In [148]:
df.loc[1]

eid                   E012
name                Bordin
gender                male
department       developer
age                     25
salary               48700
working_years            2
birth_place         Phuket
Name: 1, dtype: object

In [150]:
df.loc[[1,2,3]]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

#### Column & Row Selection

In [151]:
df.loc[1,['name','age']]

name    Bordin
age         25
Name: 1, dtype: object

In [153]:
df.loc[[1,2,3],['name','age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [156]:
df[['name','age']].loc[[1,2,3]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [158]:
df.loc[[1,2,3]][['name','age']]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39